### ISSUE TITLE
Test results from Bryan

### ISSUE THREAD

**Issue by Lin87** [oel-mediateam/sbplus#45]
https://media.uwex.edu/sandbox/ethan/sbplus/index.html

**Please check-off each task once you completed or confirmed it.**

- [x] Clear browser cache
- [x] Check the SB+ script version is 2.5.9 (displayed at about 70% down the page): https://media.uwex.edu/sandbox/ethan/sbplus/sources/scripts/storybookplus.min.js
- [x] Video loads and plays in Firefox and using HTML5 player.
- [ ] OPTIONAL On Windows: Video loads and plays in Google Chrome, using HTML5 player, and texts are clear in all resolution
- [x] Spinning loading icon is not acting weird
- [x] Go to #42 and sign off

**Comment by owlboy** [comment]
I noticed a mixed content warning when in Firefox. Even though the video played fine, I was still wondering if this was intended? I thought we were able to access all Kaltura MP4s with https://.

The example in this screenshot is this (From Slide 17): 
http://cdnbakmi.kaltura.com/p/1660872/sp/166087200/serveFlavor/entryId/1_vh2nyd0m/v/11/flavorId/1_g5nmzg4e/name/a.mp4

By looking at an example embed with https support turned on in the KMC, and transferring that subdomain to this URL I get this the following working URL:
https://cdnapisec.kaltura.com/p/1660872/sp/166087200/serveFlavor/entryId/1_vh2nyd0m/v/11/flavorId/1_g5nmzg4e/name/a.mp4

![screen shot 2015-01-20 at 11 33 01 am](https://cloud.githubusercontent.com/assets/237349/5822260/27e7b68e-a098-11e4-8d25-d58bcd21aeb6.png)

Otherwise things seem to be in order.

**Comment by Lin87** [comment]
Did some little more digging and research. I was able to make Kaltura to respond with a HTTPS URL to the video.

**Comment by Lin87** [comment]
Kaltura video is noticeably slower over HTTPS. 3 to 5 seconds delay. The worst is about less than 1 min, but the video eventually plays.
