### ISSUE TITLE
Change Default Slide Type to JPEG

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus#59]
In general, PNG files are far larger than JPEG files when it comes to the wide array of content we put in storybook slides.

I understand that PNG files will give us the best quality, but at a cost of file size, and for our purposes, the quality difference is negligible.

We also don't want to inadvertantly encourage the use of PNG files by our staff by having `<!-- default to png if not specified -->` in the Starter topic.xml.

I realize this will have to be done carefully to be sure we don't break old projects, but I feel it is very important to set this straight once and for all.

**In the mean time, lets get the Starter topic.xml to look like this:**

`<slideImgFormat>jpeg</slideImgFormat>`

**Not this:**
`<slideImgFormat /> <!-- default to png if not specified -->`

**Comment by Lin87** [comment]
The comments in the XML file are not meant to encourage or guide users. Although, they can be interpreted differently by users, but their mere existence is for documentation for me and other developers. I can remove all comments in the starter XML file.

I do not see this can be inadvertently encourage, as you put it, to our staff. If _our staff_ know that our workflow to use JPEG from now on, he/she should know to specify the image format. Granted, updating the XML file in the starter kit, _which I will do_, will make his/her job easier a little bit.

FYI, I added the "invalid" label to this issue, because this not a bug nor an enhancement.

**Comment by Lin87** [comment]
Starter topic XML file updated.
