### ISSUE TITLE
Zooming out breaks TOC

### ISSUE THREAD

**Issue by patrick-wirth** [oel-mediateam/sbplus#62]
Hi Ethan,

I'm using Firefox 40.0.  

When I zoom out, the TOC moves to the bottom left hand corner of the iFrame.  

Patrick

![screen shot 2015-08-14 at 1 07 20 pm](https://cloud.githubusercontent.com/assets/5795703/9280672/7976e814-4285-11e5-894b-ae94a0c39d24.png)

**Comment by Lin87** [comment]
I seen this issue before. There is not much that I can do because it is in an iFrame. iFrame have an absolute width and height defined and do not "scale" the content. It tries its best but not perfect.

Ethan Lin
ethan.lin@uwex.edu<mailto:ethan.lin@uwex.edu>

On Aug 14, 2015, at 1:08 PM, patrick-wirth <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Ethan,

I'm using Firefox 40.0.

When I zoom out, the TOC moves to the bottom left hand corner of the iFrame.

Patrick

[screen shot 2015-08-14 at 1 07 20 pm]<https://cloud.githubusercontent.com/assets/5795703/9280672/7976e814-4285-11e5-894b-ae94a0c39d24.png>

-

**Comment by Lin87** [comment]
There is CSS hacks for it, but...
* It is not supported by all browsers.
* It is a hit-and-miss situation.
* It works/looks great for supported browsers but terrible for those does not support.
* Require the CSS rules to be specified in the main CSS file, in this case, D2L's CSS, which we have no access.

**Comment by Lin87** [comment]
this is not a bug with the player rather the iFrame
