### ISSUE TITLE
Video Not Playing in Safari

### ISSUE THREAD

**Issue by patrick-wirth** [oel-mediateam/sbplus#67]
Hi Ethan,

Darci and I are unable to play video content in SB+ v3 in Safari (Version 9.1.1 (11601.6.17)).  I took a screen shot of the error console and attached it.

![screen shot 2016-07-25 at 10 43 49 am](https://cloud.githubusercontent.com/assets/5795703/17107424/c1094afc-5254-11e6-8265-e3636a748fbb.png)

Patrick

**Comment by Lin87** [comment]
@patrick-wirth I cannot reproduce this error on my Safari, and I have the same Safari version as yours. When you have time could you. I also have the same error messages inside the console. The videos play fine. Safari is not my default browser, and I rarely use it. So, I don't think I have special settings for Safari.

Could I take a took at your machine when you have the time?

**Comment by Lin87** [comment]
Safari does not allow cross domain cookies until user choose to go to that website first, and then it will remember to allow cookies based on the "Allow from website I visit" setting in the preference. Because the SB+ is loaded inside D2L as an iframe, user did not directly chose to go that website. So, the cookies is not read or set.
 
SB+ v3 is updated to use local storage instead of cookies.
